package com.moneytracker;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Locale; 
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

// these imports are for the "Print Report" button
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;
import java.util.Map;
import java.util.HashMap;

public class Dashboard extends javax.swing.JPanel {
    
    DefaultTableModel model;
    private double totIn = 0;
    private double totOut = 0;
    private Transaction transactionPanel;
    
    public Dashboard() {
        initComponents();
        // 1. Setup Model Tabel
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        
        // Menambahkan Kolom (Nama Kolom Bahasa Inggris)
        model.addColumn("ID");          // Index 0 (Akan disembunyikan)
        model.addColumn("Date");        // Index 1
        model.addColumn("Type");        // Index 2
        model.addColumn("Amount");      // Index 3
        model.addColumn("Category");    // Index 4
        model.addColumn("Description"); // Index 5

        // --- LOGIC MENYEMBUNYIKAN KOLOM ID ---
        // Kita set lebar kolom ke-0 menjadi 0 pixel agar tidak terlihat
        tabelTransaksi.getColumnModel().getColumn(0).setMinWidth(0);
        tabelTransaksi.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelTransaksi.getColumnModel().getColumn(0).setWidth(0);
        // --------------------------------------
        
        refreshData();
    }
    public void setTransactionPanel(Transaction transPanel) {
        this.transactionPanel = transPanel;
    }    
    
    public void refreshData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        totIn = 0;
        totOut = 0;

        try {
            Connection c = Koneksi.getKoneksi();
            ResultSet r = c.createStatement().executeQuery("SELECT * FROM transaksi ORDER BY tanggal DESC");

            while (r.next()) {
                String jenis = r.getString("jenis");
                double jml = r.getDouble("jumlah");

                // Format angka di tabel agar ada pemisah ribuan (Rp 1.000.000)
                // Kita gunakan Locale Indonesia
                String jmlFormatted = String.format(new Locale("id", "ID"), "%,.0f", jml);

                model.addRow(new Object[]{
                    r.getString("id"),      // ID tetap dimasukkan ke model (tersembunyi)
                    r.getString("tanggal"), 
                    jenis,
                    "Rp " + jmlFormatted,   // Tampilan di tabel pakai Rp
                    r.getString("kategori"),
                    r.getString("deskripsi")
                });

                if(jenis.equalsIgnoreCase("Income")) totIn += jml;
                else totOut += jml;
            }
            
            lblTotalIncome.setForeground(new java.awt.Color(0, 153, 51));
            lblTotalExpense.setForeground(new java.awt.Color(0, 153, 51));
            lblSaldoAkhir.setForeground(new java.awt.Color(0, 153, 51));
            
            // Output Dashboard (Mata Uang Rp, Label Inggris)
            // Menggunakan Locale("id", "ID") agar pemisahnya TITIK (1.000.000) bukan KOMA
            Locale indo = new Locale("id", "ID");
            lblTotalIncome.setText("Rp " + String.format(indo, "%,.0f", totIn));
            lblTotalExpense.setText("Rp " + String.format(indo, "%,.0f", totOut));
            lblSaldoAkhir.setText("Rp " + String.format(indo, "%,.0f", (totIn - totOut)));
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblTotalIncome = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblTotalExpense = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblSaldoAkhir = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 436));

        jScrollPane1.setBorder(null);

        tabelTransaksi.setBackground(new java.awt.Color(245, 245, 245));
        tabelTransaksi.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 140));

        jLabel1.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        jLabel1.setText("Income");

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(245, 245, 245));

        lblTotalIncome.setEditable(false);
        lblTotalIncome.setBackground(new java.awt.Color(245, 245, 245));
        lblTotalIncome.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lblTotalIncome.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        lblTotalIncome.setForeground(new java.awt.Color(245, 245, 245));
        lblTotalIncome.setCaretColor(new java.awt.Color(245, 245, 245));
        lblTotalIncome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblTotalIncome.setPreferredSize(new java.awt.Dimension(62, 50));
        lblTotalIncome.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lblTotalIncome.setSelectionColor(new java.awt.Color(245, 245, 245));
        jScrollPane2.setViewportView(lblTotalIncome);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setPreferredSize(new java.awt.Dimension(230, 140));

        jLabel2.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        jLabel2.setText("Expense");

        jScrollPane3.setBorder(null);

        lblTotalExpense.setEditable(false);
        lblTotalExpense.setBackground(new java.awt.Color(245, 245, 245));
        lblTotalExpense.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lblTotalExpense.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        lblTotalExpense.setForeground(new java.awt.Color(255, 153, 153));
        lblTotalExpense.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblTotalExpense.setPreferredSize(new java.awt.Dimension(62, 50));
        lblTotalExpense.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(lblTotalExpense);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));
        jPanel5.setPreferredSize(new java.awt.Dimension(230, 140));

        jLabel3.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        jLabel3.setText("Total");

        jScrollPane4.setBorder(null);

        lblSaldoAkhir.setEditable(false);
        lblSaldoAkhir.setBackground(new java.awt.Color(245, 245, 245));
        lblSaldoAkhir.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lblSaldoAkhir.setFont(new java.awt.Font("Google Sans", 1, 24)); // NOI18N
        lblSaldoAkhir.setForeground(new java.awt.Color(204, 255, 217));
        lblSaldoAkhir.setCaretColor(new java.awt.Color(204, 255, 217));
        lblSaldoAkhir.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblSaldoAkhir.setPreferredSize(new java.awt.Dimension(62, 50));
        lblSaldoAkhir.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(lblSaldoAkhir);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Print Report");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(700, 100));

        jLabel5.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel5.setText("Dashboard");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel7, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked

    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();

            params.put("income", totIn);
            params.put("expense", totOut);
            params.put("total", totIn - totOut);

            InputStream is = getClass().getResourceAsStream("/report/moneyTrackerReport.jasper");
            Connection c = Koneksi.getKoneksi();

            JasperPrint jp = JasperFillManager.fillReport(is, params, c);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane lblSaldoAkhir;
    private javax.swing.JTextPane lblTotalExpense;
    private javax.swing.JTextPane lblTotalIncome;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
